package:
  name: xpdview
  version: '0.1.0'

source:
  git_rev: conda-build
  git_url: https://github.com/chiahaoliu/xpdView.git

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - matplotlib

test:
    import:
      - xpdview.viewer

about:
  home: https://github.com/xpdAcq/xpdView
  license: BSD
