package:
  name: xpdview
  version: '0.1.0'

source:
  git_rev: conda-build
  git_url: https://github.com/chiahaoliu/xpdView.git

requirements:
  build:
    - python
    - setuptools
  
  run:
    - python
    - matplotlib >=2.0.0
    - pyqt >=4.11.4

test:
    import:
      - xpdview.viewer

about:
  home: https://github.com/xpdAcq/xpdView
  license: BSD
